version: "3"
services:
  mongo:
    image: library/mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  redis:
    image: library/redis:latest
    ports:
    - 6379:6379
volumes:
  db: